# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 5cf62b094b9169081ad5f96136f405c07446ead78c58f8fc8bd7a9b52877d97c4a7f751c578de5c836b8860a5d6d0a8c5cc8c0e5c28c69998640bfe4a143454b

test:
  secret_key_base: 7f7268463ba6daf46a9803cf265fd0c57198352fb54933502dde7a9d20abcfd6e4752f0390e94f8cf6261a9c0494dfd69a24f851e397a5be885caae6c309ab0e

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
